- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
Update for latest angularjs-eclipse
> [JBIDE-19002] Update Tern.java (TP) and AngularJS (Central) IDE v.0.8

- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
Fix updates angular feature to released version 0.7.0.201412021122
> [JBIDE-19045] Update Tern.java and AngularJS 0.7.0

- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
Update angularjs-eclipse to 0.9.0.201502172152/
> {JBIDE-19320] Update angularjs-eclipse to 0.9.0-SNAPSHOT

- README.discovery.sites.adoc
- jbdevstudio/com.jboss.jbds.central.discovery.earlyaccess/plugin.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
JBIDE-...
...20100 add missing images for JBT discovery; add "Yet" and fix
connector categories / groups
> JBIDE-20662: Mars.1 RC3 (not Neon M1)

- jbtcentraltarget/multiple/jbtcentral-multiple.target
JBIDE-21651 bump up to latest mars.2.RC4
> JBIDE-21651 bump up to latest mars.2.RC4

- README.discovery.sites.adoc
- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/plugin.xml
- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/META-INF/MANIFEST.MF
- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/plugin.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
Signed-off-by:...
bump to to 4.5.2 / 11.2.0
Signed-off-by: nickboldt <nboldt@redhat.com>
> bump to to 4.5.2 / 11.2.0

- devstudio/com.jboss.devstudio.central.discovery/plugin.properties
- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.properties
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> [JBIDE-25770] - Remove "Hybrid Mobile Project" wizard from Central

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> JBIDE-26388 - prepare for first eclipse 4.10-based target platform

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- pom.xml
> JBIDE-26479 - prepare for first 4.11 target platform

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- SpringIde 3.9.7
- EclipseCS 8.7.0
- SonarLint 4.0.0
> JBIDE-26477 - Update TP

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
> JBIDE-26565 - Update 4.11.0.Final TP

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> JBIDE-26580: nodeclipse.org does not respond anymore

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- pom.xml
> Prepare for 4.12.0.AM1 / 12.12.0.AM1

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
> Fix bundle identifiers to match 4.12.0

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- SpringIde 3.9.8.201903260800-RELEASE
> JBIDE-26622: Update 4.12.0.AM1 TP

- jbtcentraltarget/multiple/jbtcentral-multiple.target
> JBDS-4783: Remediation page when installing central from zip

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> [JBIDE-26822] corrected OpenShift 3 -> OpenShift to match support for v4

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
> JBIDE-26842: Update 4.13.0.Final Target Platform for 2019-09.GA

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> Prepare TP for 4.14.0.AM1 / 12.14.0.AM1

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
Signed-off-by: Stéphane Bouchet <sbouchet@redhat.com>
> JBIDE-26890: fix nodeclipse repository

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/plugin.xml
> JBIDE-26914 : fixed fabric8-analytics update site

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/plugin.xml
> JBIDE-26914: fixed fabric8-analytics update site for earlyaccess 

- jbtcentraltarget/multiple/jbtcentral-multiple.target
> JBIDE-26972: fix central dependency

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
> Prepare TP for 4.14.0.Final / 12.14.0.Final

- jbtcentraltarget/multiple/jbtcentral-multiple.target
> JBIDE-26973 : move google.inject to base Target Platform

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> JBIDE-26987: Deprecate vpe/forge/jst components

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> Prepare TP for 4.15.0.AM1 / 12.15.0.AM1

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> Prepare TP for 4.15.0.Final / 12.15.0.GA

- jbtcentraltarget/multiple/jbtcentral-multiple.target
> JBIDE-27151: update SpringIDE

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> Prepare TP for 4.16.0.AM1 / 12.16.0.AM1

- jbtcentraltarget/multiple/jbtcentral-multiple.target
> JBIDE-27253: Update 4.16.0.AM1 Target Platform for 2020-06.M2

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> JBIDE-27317: Deprecate Android Development Tools

- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> JBIDE-27377: fix certificationId for ADT

- build.xml
> Move build to jdk11.

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> JBIDE-27453: Update 4.17.0.AM1 Target Platform for 2020-09 RC1

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
> JBIDE-27466: Update 4.17.0.Final TP for 2020-09

- devstudio/com.jboss.devstudio.central.discovery/plugin.properties
> JBIDE-27572: Cannot load bundle com.jboss.devstudio.central.discovery

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
> JBIDE-27604 : fix certificationId

- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
> JBIDE-27787: Remove nodeclipse from central

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> JBIDE-28008: Update 4.21.0.Final Target Platform for 2021-09 GA

- .github/workflows/build_test.yml
- build.xml
- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml
- devstudio/com.jboss.devstudio.central.discovery/plugin.xml
- devstudio/com.jboss.devstudio.central.discovery/pom.xml
- devstudio/pom.xml
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/plugin.xml
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> JBIDE-26888 : Replace http access to https

- devstudio/com.jboss.devstudio.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- devstudio/com.jboss.devstudio.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
> JBIDE-28475: migrate mylyn discovery

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/pom.xml
> JBIDE-28582: Fix discovery build after switch to Java 17

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
> JBIDE-28621: fix discovery after TP update

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
> JBIDE-28635 : update central targetplatform

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target
- jbtearlyaccesstarget/multiple/pom.xml
- jbtearlyaccesstarget/pom.xml
- pom.xml
> JBIDE-28727: update central tp for 4.26.0.AM1

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/plugin.xml
> JBIDE-28096: added Deprecated label to AngularJS

- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
> JBIDE-28808: Update TP for 2022-12

- .github/workflows/build_test.yml
> Update action to add central discovery connectors build

- jbosstools/org.jboss.tools.central.discovery.earlyaccess/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml
- jbosstools/org.jboss.tools.central.discovery/META-INF/MANIFEST.MF
- jbosstools/org.jboss.tools.central.discovery/pom.xml
- jbosstools/pom.xml
- jbtcentraltarget/multiple/jbtcentral-multiple.target
- jbtcentraltarget/multiple/pom.xml
- jbtcentraltarget/pom.xml
- pom.xml
> JBIDE-28745: remove conflicting boucycastle bundle
